name: CI/CD for Vite React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-vite-react-app:latest .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to registry
        run: |
          docker tag my-vite-react-app:latest my-docker-registry/my-vite-react-app:latest
          docker push my-docker-registry/my-vite-react-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Docker image to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_SSH_KEY }}
          script: |
            docker pull my-docker-registry/my-vite-react-app:latest
            docker stop my-vite-react-app || true
            docker rm my-vite-react-app || true
            docker run -d --name my-vite-react-app -p 5000:5000 my-docker-registry/my-vite-react-app:latest
